Ejercicio 31:

Cree una matriz aleatoria de 3x3 y reemplace todos los valores mayores que 0,5 con 1 y todos los demás con 0.

In [6]:
import numpy as np 
matris=np.random.random((3,3))
print("___"*10)
print(matris)

matris[matris>=0.5]=1
matris[matris<0.5]=0
print("___"*10)
print(matris)
print("___"*10)

______________________________
[[0.94849049 0.84492948 0.20369111]
 [0.77945724 0.27378454 0.47988249]
 [0.85479196 0.69398481 0.1679476 ]]
______________________________
[[1. 1. 0.]
 [1. 0. 0.]
 [1. 1. 0.]]
______________________________


Ejercicio 32:

Encuentre los índices de los N valores máximos superiores en una matriz 1D.

In [7]:
import numpy as np 
matris=np.array([10, 5, 8, 20, 15])
indices_superiores=np.argsort(matris)[-2:]
print(indices_superiores)

[4 3]


Ejercicio 33:

Calcular la media de cada columna en una matriz 2D.

In [14]:
import numpy as np 
matris=np.random.random((4,3))
media=np.mean(matris,axis=0)
print(media)


[0.32801005 0.44937001 0.49092389]


Ejercicio 34:

Normalizar los valores en cada columna de una matriz 2D.

In [17]:
import numpy as np
matris=np.random.random((4,3))
print ("___"*8)
print(matris)
print ("___"*8)
normalizado=(matris-np.mean(matris,axis=0))/np.std(matris,axis=0)
print(normalizado)


________________________
[[0.33930758 0.86850262 0.91117641]
 [0.23285103 0.61648615 0.09143731]
 [0.66359058 0.36893928 0.18937918]
 [0.86886507 0.85652042 0.78944668]]
________________________
[[-0.73673705  0.93294342  1.15754043]
 [-1.15649716 -0.29874229 -1.12443037]
 [ 0.54191661 -1.50858369 -0.85178205]
 [ 1.35131759  0.87438256  0.81867199]]


Ejercicio 35:

Concatenar dos matrices 1D.

In [18]:
import numpy as np 

mat1=np.array([1,2,3])
mat2=np.array([4,5,6])
matris=np.concatenate((mat1,mat2))
print(matris)

[1 2 3 4 5 6]


Ejercicio 36:

Crea una matriz 2D con valores aleatorios y ordena cada fila.

In [21]:
import numpy as np 
matris=np.random.random((2,6))
orden=np.sort(matris,axis=1)
print(matris)
print("___"*10)
print(orden)


[[0.64306188 0.10080345 0.6937437  0.87461677 0.81661659 0.56370208]
 [0.16857194 0.04307269 0.87825451 0.74886679 0.64702317 0.293409  ]]
______________________________
[[0.10080345 0.56370208 0.64306188 0.6937437  0.81661659 0.87461677]
 [0.04307269 0.16857194 0.293409   0.64702317 0.74886679 0.87825451]]


Ejercicio 37:

Calcular el error cuadrático medio entre dos matrices.

In [23]:
import numpy as np 
mat1=np.array([1,2,3,4])
mat2=np.array([2,3,4,5])
medio=np.mean((mat1-mat2)**2)
print(medio)

1.0


Ejercicio 38:

Reemplaza todos los valores negativos en una matriz con 0.

In [24]:
import numpy as np 
mat1=np.array([[-1, 2, -3, 4, -5]])
mat1[mat1<0]=0
print (mat1)

[[0 2 0 4 0]]


Ejercicio 39:

Encuentra los percentiles 5 y 95 de una matriz.

In [26]:
import numpy as np
mat1=np.random.random(10)

percentil5=np.percentile(mat1,5)
percentil95=np.percentile(mat1,95)
print(f"matris: {mat1}")
print(f"percentil 5: {percentil5}")
print(f"percentil 95: {percentil95}")

matris: [5.22469025e-01 7.10143081e-01 5.72351109e-01 9.21853180e-01
 9.78038888e-01 6.65028090e-01 6.62577166e-01 8.19104099e-04
 4.33562709e-01 7.65141034e-01]
percentil 5: 0.19555372620103592
percentil 95: 0.9527553192006375


Ejercicio 40:

Crea una matriz aleatoria de 2x2 y calcula su determinante.

In [ ]:
import numpy as np 
mat1=np.random.random((2,2))
determinante=np.linalg.det(mat1)
print(determinante)
