Ejercicio 41:

Cuente el número de elementos de una matriz que son mayores que la media.

In [1]:
import numpy as np 
mat1=np.array([1,2,3,4,5,6,7,8,9,10])

mayores_media=np.sum(mat1>np.mean(mat1))
print(mayores_media)

5


Ejercicio 42:

Calcular la raíz cuadrada de cada elemento de una matriz 1D.

In [3]:
import numpy as np
mat1=np.array([4, 9, 16, 25])
raiz=np.sqrt(mat1)
print(mat1)
print(raiz)

[ 4  9 16 25]
[2. 3. 4. 5.]


Ejercicio 43:

Crea una matriz de 3x3 y calcula la raíz cuadrada de la matriz.

In [6]:
import numpy as np 
mat1=np.random.random((3,3))
raiz=np.linalg.matrix_power(mat1,2)
print(mat1)
print("___"*15)
print(raiz)

[[0.73505322 0.52871738 0.46337886]
 [0.81906956 0.11717622 0.5704309 ]
 [0.58941867 0.28904222 0.36516575]]
_____________________________________________
[[1.24648371 0.58452458 0.81141495]
 [1.03425782 0.6116652  0.65468229]
 [0.88523529 0.45105309 0.57134879]]


Ejercicio 44:

Convierte el tipo de datos de una matriz a flotante.

In [7]:
import numpy as np 
mat1=np.array([1,2,3,4,5],dtype=int)
float=mat1.astype(float)
print(float)

[1. 2. 3. 4. 5.]


Ejercicio 45:

Calcular los valores absolutos elemento por elemento de una matriz.

In [8]:
import numpy as np 
mat1=np.array([-1,-2,-3,-4,-5])
abs=np.abs(mat1)
print(abs)

[1 2 3 4 5]


Ejercicio 46:

Encuentra los índices donde coinciden los elementos de dos matrices.

In [1]:
import numpy as np 

mat1=np.array([1, 2, 3, 4, 5])
mat2=np.array([3, 2, 8, 4, 5])
coinciden=np.where(mat1==mat2)
print(coinciden)

(array([1, 3, 4]),)


Ejercicio 47:

Calcular la suma acumulada de elementos en una matriz 1D.

In [7]:
import numpy as np 
mat1=np.array([1,2,3,4,5])
suma=np.cumsum(mat1)
print(suma)

[ 1  3  6 10 15]


Ejercicio 48:

Calcular la inversa de una matriz 2x2.

In [8]:
import numpy as np
mat1=np.random.random((2,2))
inversa=np.linalg.inv(mat1)
print(inversa)

[[ 66.06206119 -38.55987391]
 [ -7.77091435   6.38752478]]


Ejercicio 49:

Cuente el número de elementos distintos de cero en una matriz 2D.

In [11]:

import numpy as np 

mat1=np.array([[0, 1, 0], [2, 0, 3], [0, 4, 0]])
nocero=np.count_nonzero(mat1)
print(mat1)
print("___"*8)
print(nocero)

[[0 1 0]
 [2 0 3]
 [0 4 0]]
________________________
4


Ejercicio 50:

Cree una matriz 2D y reemplace todos los valores nan con 0.

In [14]:
import numpy as np
mat1=np.array([[1, np.nan, 3], [4, 5, np.nan], [7, 8, 9]])
mat1[np.isnan(mat1)]=0
print(mat1)


[[1. 0. 3.]
 [4. 5. 0.]
 [7. 8. 9.]]
