Ejercicio 51:

Encuentra el coeficiente de correlación entre dos matrices.

In [1]:
import numpy as np 

arr1=np.array([1, 2, 3, 4, 5])
arr2=np.array([3, 4, 5, 6, 7])
correlacion=np.corrcoef(arr1,arr2)[0,1]
print(correlacion)

0.9999999999999999


Ejercicio 52:

Cree una matriz 1D y elimine todos los valores duplicados.

In [2]:
import numpy as np 
arr1=np.array([1, 2, 3, 2, 4, 5, 1])
unico=np.unique(arr1)
print(unico)

[1 2 3 4 5]


Ejercicio 53:

Calcular el producto elemento por elemento de dos matrices.

In [3]:
import numpy as np 

arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
producto=np.multiply(arr1,arr2)
print(producto)

[ 4 10 18]


Ejercicio 54:

Calcular la desviación estándar de cada columna en una matriz 2D.

In [5]:
import numpy as np 

matris=np.random.random((3,4))
print(matris)
desviacion=np.std(matris,axis=0)
print("____"*10)
print(desviacion)

[[0.215984   0.15612584 0.49650103 0.54589918]
 [0.31172149 0.32403629 0.09887948 0.01959276]
 [0.15921921 0.84030753 0.55977139 0.49806828]]
________________________________________
[0.06293281 0.29113466 0.20399548 0.23763302]


Ejercicio 55:

Cree una matriz 2D y establezca todos los valores por encima de un umbral determinado en ese umbral.

In [6]:
import numpy as np 

matris=np.random.random((3,4))
umbral=0.7
matris[matris<0.7]=umbral
print(matris)

[[0.7        0.82536383 0.7        0.89467652]
 [0.82094549 0.73222589 0.7        0.7       ]
 [0.7        0.7        0.77250807 0.7       ]]


Ejercicio 56:

Crea una matriz aleatoria de 5x5 y reemplaza el valor máximo por -1.

In [8]:
import numpy as np

matris=np.random.random((5,5))
maximo=np.max(matris)
matris[matris==maximo]=-1
print(matris)

[[ 0.02168744  0.03830365 -1.          0.66845277  0.30843537]
 [ 0.6846045   0.70696772  0.39627785  0.62286424  0.17189706]
 [ 0.67699297  0.7701919   0.72069554  0.45806517  0.8449909 ]
 [ 0.2087379   0.20511276  0.64901799  0.74721921  0.03391017]
 [ 0.02875003  0.03283499  0.90810958  0.90987924  0.20064278]]


Ejercicio 57:

Convierte una matriz 1D de temperaturas Fahrenheit a Celsius.

In [9]:
import numpy as np 
Fahrenhei=np.array([32, 68, 100, 212])
celsius=(Fahrenhei-32)* 5/9
print(f"temperatura en Fahrenhei: {Fahrenhei}")
print(f"temperatura en Celsius: {celsius}")

temperatura en Fahrenhei: [ 32  68 100 212]
temperatura en Celsius: [  0.          20.          37.77777778 100.        ]


Ejercicio 58:

Calcular el producto externo de dos matrices.

In [10]:
import numpy as np 
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
prod=np.outer(arr1,arr2)
print(prod)

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


Ejercicio 59:

Crea una matriz 1D con 10 valores equidistantes entre 0 y 1.

In [11]:
import numpy as np 
arr1=np.linspace(0,1,10)
print(arr1)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


Ejercicio 60:

Calcular el producto vectorial de dos matrices tridimensionales.

In [12]:
import numpy as np 
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
producto_vectorial= np.cross(arr1, arr2)
print(producto_vectorial)

[-3  6 -3]
