Ejercicio 71:

Cree una matriz 1D y establezca los valores entre 10 y 20 en 0.

In [3]:
import numpy as np

arr=np.array([5, 15, 12, 18, 25])
arr[(arr>=10) & (arr<=20)]=0
print(arr)



[ 5  0  0  0 25]


Ejercicio 72:

Calcular el seno hiperbólico inverso de cada elemento de una matriz 1D.

In [4]:
import numpy as np 
array=np.array([1, 2, 3, 4])
inverso=np.arcsinh(arr)
print(inverso)

[2.31243834 0.         0.         0.         3.91242277]


Ejercicio 73:

Calcular el producto Kronecker de dos matrices.

In [5]:
import numpy as np 

arr1=np.array([1,2])
arr2=np.array([3,4])
pro=np.kron(arr1,arr2)
print(pro)

[3 4 6 8]


Ejercicio 74:

Calcular la desviación absoluta media de una matriz 1D.

In [6]:
import numpy as np

arr=np.array([1,2,3,4,5])
desviacion=np.mean(np.abs(arr - np.mean(arr)))
print(arr)

[1 2 3 4 5]


Ejercicio 75:

Crea una matriz de 3x3 y establece todos los valores por encima de la diagonal principal en cero.

In [ ]:
import numpy as np 

matris=np.random.random((3,3))
matris[np.triu_indices(3, 1)] = 0
print(matris)