Ejercicio 61:

Calcular el percentil a lo largo de un eje específico de una matriz 2D.

In [1]:
import numpy as np 

matris=np.random.random((3,2))
percentil=np.percentile(matris,75,axis=1)
print(percentil)

[0.50627695 0.49255984 0.90168811]


Ejercicio 62:

Crea una matriz 1D y agrega un borde de 0 a su alrededor.

In [2]:
import numpy as np 
matris=np.array([1,2,3,4])
borde=np.pad(matris,(1,1), mode='constant',constant_values=0)
print(borde)

[0 1 2 3 4 0]


Ejercicio 63:

Calcular el histograma de una matriz 1D.

In [15]:
import numpy as np

matris=np.array([1, 1, 2, 2, 2, 3, 3, 3, 3])
hist, bins = np.histogram(matris, bins=[1, 2, 3, 4])
print("histograma:", hist)
print("bordes:", bins)

histograma: [2 3 4]
bordes: [1 2 3 4]


Ejercicio 64:

Crea una matriz 2D con valores aleatorios y normaliza cada fila.

In [16]:
import numpy as np 
matris=np.random.random((4,3))
normalizada = matris / np.linalg.norm(matris, axis=1, keepdims=True)
print(normalizada)

[[0.43515676 0.12287132 0.89193118]
 [0.84947682 0.4182402  0.32165862]
 [0.3609004  0.16826292 0.91729956]
 [0.47716992 0.71416279 0.51213316]]


Ejercicio 65:

Crea una matriz 2D aleatoria y ordenala por la segunda columna.

In [18]:
import numpy as np 

matris=np.random.random((3,4))
sorted_matrix_by_column2 = matris[matris[:, 1].argsort()]
print(sorted_matrix_by_column2)

print(" ##### "*8)
print(matris)

[[0.55574279 0.1148732  0.89035005 0.55381456]
 [0.94013242 0.31550757 0.98562589 0.86092083]
 [0.99133887 0.7683321  0.96268659 0.25868721]]
 #####  #####  #####  #####  #####  #####  #####  ##### 
[[0.94013242 0.31550757 0.98562589 0.86092083]
 [0.99133887 0.7683321  0.96268659 0.25868721]
 [0.55574279 0.1148732  0.89035005 0.55381456]]


Ejercicio 66:

Calcular el determinante de una matriz de 3x3.

In [20]:
import numpy as np 
matris=np.random.random((3,3))
determiante=np.linalg.det(matris)
print(matris)
print("##########"*8)
print(determiante)

[[0.04837988 0.93785158 0.91751033]
 [0.67639767 0.21541604 0.17411522]
 [0.3023623  0.86255698 0.26201076]]
################################################################################
0.35417306134132404


Ejercicio 67:

Calcular la exponenciación elemento por elemento de una matriz 1D.

In [21]:
import numpy as np 

matris=np.array([2,3,4])
exponen=np.exp(matris)
print(exponen)

[ 7.3890561  20.08553692 54.59815003]


Ejercicio 68:

Calcular la norma de Frobenius de una matriz 2D.

In [22]:
import numpy as np
matrix = np.random.random((3, 4))
frobenius_norm = np.linalg.norm(matrix)
print(frobenius_norm)

1.536447492919894


Ejercicio 69:

Crea una matriz 2D con valores aleatorios y reemplaza el valor máximo por el mínimo.

In [23]:
import numpy as np 
matris=np.random.random((3,4))
max_value_index = np.unravel_index(np.argmax(matris), matris.shape)
min_value = np.min(matris)
matris[max_value_index] = min_value
print(matris)


[[0.19366412 0.37879985 0.25544103 0.16820004]
 [0.5351665  0.01708153 0.52730404 0.01708153]
 [0.51120247 0.63609984 0.23097695 0.67465819]]


Ejercicio 70:

Calcular la multiplicación de matrices de dos matrices 2D.

In [24]:
import numpy as np
matrix1 = np.random.random((3, 4))
matrix2 = np.random.random((4, 5))
matrix_multiplication = np.dot(matrix1, matrix2)
print(matrix_multiplication)

[[0.71201937 0.52203248 0.41084707 0.65331756 0.33136441]
 [0.47186991 0.93693819 0.89521347 1.11535685 0.6432528 ]
 [0.97846868 0.98515208 0.77787502 0.92065995 0.49410579]]
