Ejercicio 21:

Encuentra la media de cada fila en una matriz 2D.

In [3]:
import numpy as np 

matris=np.random.random((3,4))
print(matris)
media=np.mean(matris,axis=1)
print("***"*8)
print(media)

[[0.9583288  0.10365984 0.66163071 0.51312509]
 [0.59759184 0.68935465 0.54433279 0.60219198]
 [0.09924423 0.53725885 0.1224979  0.40401071]]
************************
[0.55918611 0.60836781 0.29075293]


Ejercicio 22:

Crea una matriz aleatoria de 4x4 y extrae los elementos diagonales.

In [9]:
import numpy as np 
matris=np.random.random((4,4))
print(matris)
diagonal=np.diag(matris)
print("***"*20)
print(diagonal)


[[0.26192601 0.84362602 0.03119823 0.76760632]
 [0.49535969 0.20099693 0.63696383 0.67405481]
 [0.72691004 0.14196598 0.21348316 0.11082645]
 [0.42911103 0.29525358 0.28219943 0.68628853]]
************************************************************
[0.26192601 0.20099693 0.21348316 0.68628853]


Ejercicio 23:

Cuente el número de ocurrencias de un valor específico en una matriz.

In [10]:
import numpy as np
matris=np.array([1, 2, 3, 4, 2, 3, 2, 1])
ocurrencias=np.count_nonzero(matris==2)
print(ocurrencias)

3


Ejercicio 24:

Reemplazar todos los valores en una matriz 1D con la media de la matriz.

In [11]:
import numpy as np
matris=np.array([[10, 20, 30, 40, 50]])
matris[:]=np.mean(matris)
print(matris)

[[30 30 30 30 30]]


Ejercicio 25:

Encuentra los índices de los valores máximo y mínimo en una matriz 1D.

In [12]:
import numpy as np 
matris=np.array([5, 2, 8, 1, 7])
maximo=np.max(matris)
minimo=np.min(matris)

print(maximo)
print(minimo)

8
1


Ejercicio 26:

Crea una matriz 2D con 1 en el borde y 0 dentro.

In [13]:
import numpy as np 
matris=np.ones((5,5))
matris[1:-1,1:-1]=0
print(matris)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Ejercicio 27:

Encuentre los valores únicos y sus conteos en una matriz 1D.

In [14]:
import numpy as np 
matris=np.array([1, 2, 3, 2, 4, 1, 5, 4, 6])
valore_unicos, contador = np.unique(matris, return_counts=True)
print(valore_unicos)
print(contador)

[1 2 3 4 5 6]
[2 2 1 2 1 1]


Crea una matriz de 3x3 con valores que van del 0 al 8.

In [16]:
import numpy as np 
matris=np.arange(9).reshape(3,3)
print(matris)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Ejercicio 29:

Calcular la exponencial de todos los elementos en una matriz 1D.

In [20]:
import numpy as np 
matris=np.array([1,2,3,4,5])

exp=np.exp(matris)
print(exp)

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


Intercambiar dos filas en una matriz 2D.

In [22]:
import numpy as np
matrix = np.arange(12).reshape(3, 4)
matrix[[0, 1]] = matrix[[1, 0]]
print(matrix)

[[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]]
