Ejercicio 61:

Calcular el percentil a lo largo de un eje específico de una matriz 2D.

In [1]:
import numpy as np 

matris=np.random.random((3,2))
percentil=np.percentile(matris,75,axis=1)
print(percentil)

[0.50627695 0.49255984 0.90168811]


Ejercicio 62:

Crea una matriz 1D y agrega un borde de 0 a su alrededor.

In [2]:
import numpy as np 
matris=np.array([1,2,3,4])
borde=np.pad(matris,(1,1), mode='constant',constant_values=0)
print(borde)

[0 1 2 3 4 0]


Ejercicio 63:

Calcular el histograma de una matriz 1D.

In [15]:
import numpy as np

matris=np.array([1, 1, 2, 2, 2, 3, 3, 3, 3])
hist, bins = np.histogram(matris, bins=[1, 2, 3, 4])
print("histograma:", hist)
print("bordes:", bins)

histograma: [2 3 4]
bordes: [1 2 3 4]


Ejercicio 64:

Crea una matriz 2D con valores aleatorios y normaliza cada fila.

In [16]:
import numpy as np 
matris=np.random.random((4,3))
normalizada = matris / np.linalg.norm(matris, axis=1, keepdims=True)
print(normalizada)

[[0.43515676 0.12287132 0.89193118]
 [0.84947682 0.4182402  0.32165862]
 [0.3609004  0.16826292 0.91729956]
 [0.47716992 0.71416279 0.51213316]]


Ejercicio 65:

Crea una matriz 2D aleatoria y ordenala por la segunda columna.

In [ ]:
import numpy as np 

matris=np.random.random((3,4))
sorted_matrix_by_column2 = matris[matris[:, 1].argsort()]
print(sorted_matrix_by_column2)