Invertir una matriz 1D (el primer elemento se convierte en el último).

In [1]:
import numpy as np 
arr=np.arange(10)
invertir=np.flip(arr)
print(arr)
print("___"*8)
print(invertir)

[0 1 2 3 4 5 6 7 8 9]
________________________
[9 8 7 6 5 4 3 2 1 0]


Ejercicio 12:

Crea una matriz identidad de 3x3.

In [7]:
import numpy as np 
matris=np.eye(3)
print(matris)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Ejercicio 13:

Remodelar una matriz 1D a una matriz 2D con 5 filas y 2 columnas.

In [13]:
import numpy as np
matris=np.arange(10).reshape(5,2)
print(matris)


[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


Ejercicio 14:

Apila dos matrices verticalmente.

In [17]:
import numpy as pn 
mat1=np.arange(5)

print(mat1)
mat2=np.arange(5,10)
print("___"*10)
print(mat2)
print("___"*10)
apilado=np.vstack((mat1,mat2))
print(apilado)
print("___"*10)


[0 1 2 3 4]
______________________________
[5 6 7 8 9]
______________________________
[[0 1 2 3 4]
 [5 6 7 8 9]]
______________________________


Ejercicio 15:

Obtener los elementos comunes entre dos matrices.

In [24]:
import numpy as np 
matris1=np.array([1,2,3,4,5])
matris2=np.array([3,4,5,6,7])
igual=np.intersect1d(matris1,matris2)
print(igual)


[3 4 5]


Ejercicio 16:

Cree una matriz de 5x5 con valores de fila que van del 0 al 4.

In [25]:
import numpy as np
matris = np.zeros((5, 5))
matris += np.arange(5)
print(matris)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


Ejercicio 17:

Encuentra el índice del valor máximo en una matriz 1D.

In [28]:
import numpy as np 
matris= np.array([3, 7, 1, 10, 4])
valor_max=np.argmax(matris)
print(valor_max)

3


Ejercicio 18:

Normaliza los valores en una matriz 1D entre 0 y 1.

In [30]:
import numpy as np 
tuki=np.array([2, 5, 10, 3, 8])
areglo=(tuki-np.min(tuki))/(np.max(tuki)-np.min(tuki))
print(areglo)
min=np.min(tuki)
max=np.max(tuki)
print(min,max)

[0.    0.375 1.    0.125 0.75 ]
2 10


Ejercicio 19:

Calcular el producto escalar de dos matrices.

In [32]:
import numpy as np 

mat1=np.array([1,2,3])
mat2=np.array([4,5,6])
producto_escalar=np.dot(mat1,mat2)
print(producto_escalar)

32


Ejercicio 20:

Cuente el número de elementos de una matriz dentro de un rango específico.

In [34]:
import numpy as np
mat1=np.array([2, 5, 8, 10, 12, 15])
cont=np.sum((mat1>=5)&(mat1<=12))
print(cont)

4
