Ejercicio 1:

Crea una matriz 1D con valores que van del 0 al 9.

Con un solo número: np.arange(10) Crea números desde el 0 hasta el 9 (el 10 no se incluye).
Resultado: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Con inicio y fin: np.arange(5, 11) Empieza en 5 y termina antes del 11.

Resultado: [5, 6, 7, 8, 9, 10]

Con "paso" (saltos): np.arange(0, 21, 5) Va del 0 al 20, saltando de 5 en 5.

Resultado: [0, 5, 10, 15, 20]

In [3]:
import numpy as np 
arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


Ejercicio 2:

Convierte una matriz 1D en una matriz 2D con 2 filas.

np.arange(10) crea una lista simple del 0 al 9: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9].
reshape(2, -1) le dice a Python: "Quiero que esto tenga 2 filas".
El -1 es un comodín. Le estás diciendo a NumPy:"Yo sé que quiero 2 filas, vos calculá automáticamente cuántas columnas se necesitan para que entren los 10 elementos".Como tienes 10 elementos y pediste 2 filas, NumPy hace la cuenta ($10 / 2 = 5$) y decide que el array debe tener 5 columnas.


In [4]:
import numpy as np 
arr=np.arange(10).reshape(2,-1)
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


Ejercicio 3:

Multiplica una matriz de 5x3 por una matriz de 3x2.

In [5]:
import numpy as np 
mat1= np.random.random((5, 3))
print(mat1)
print("--"*8)
mat2=np.random.random((3, 2))
print("--"*8)
print(mat2)
print("--"*8)
resultado=np.dot(mat1,mat2)
print(resultado)

[[0.65705763 0.84112507 0.5916554 ]
 [0.55974567 0.47446115 0.28742672]
 [0.39595404 0.16332432 0.60021048]
 [0.53040275 0.3651351  0.77971642]
 [0.48514939 0.5705446  0.58203972]]
----------------
----------------
[[0.89909491 0.61716266]
 [0.18866394 0.31582693]
 [0.52870188 0.63225205]]
----------------
[[1.06225646 1.04523672]
 [0.74474124 0.67702787]
 [0.70414608 0.67543457]
 [0.95800778 0.93564157]
 [0.85156203 0.84760524]]


Ejercicio 4:

Extrae todos los números impares de una matriz del 1 al 10.

In [ ]:
import numpy as np 
mat=np.arange(11)
print(mat)
impares=mat[mat%2!=0]
print(impares)


[ 0  1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


Ejercicio 5:

Reemplace todos los números impares en una matriz del 1 al 10 con -1.

In [7]:
import numpy as np 
mat1=np.arange(11)
print(mat1)
mat1[mat1%2!=0]=-1
print(mat1)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0 -1  2 -1  4 -1  6 -1  8 -1 10]


Ejercicio 6:

Convierte una matriz 1D en una matriz booleana donde todos los valores positivos se convierten en verdaderos.

In [8]:
import numpy as np 
mat=np.array([-1, 2, 0, -4, 5])
boleano_mat=mat>0
print(mat)
print(boleano_mat)

[-1  2  0 -4  5]
[False  True False False  True]


Ejercicio 7:

Reemplace todos los números pares en una matriz 1D con su valor negativo.

In [9]:
import numpy as np 
mat1=np.arange(11)
print (mat1)
mat1[mat1%2==0] *= -1
print(mat1)


[ 0  1  2  3  4  5  6  7  8  9 10]
[  0   1  -2   3  -4   5  -6   7  -8   9 -10]


Ejercicio 8:

Crea una matriz aleatoria de 3x3 y normalízala.

In [10]:
import numpy as np
matris=np.random.random((3,3))
norma=(matris- np.mean(matris))/np.std(matris)
print(matris)
print("_"*38)
print(norma)


[[0.79223095 0.28899866 0.70185482]
 [0.33908109 0.75423061 0.69840224]
 [0.96611763 0.66674169 0.33705603]]
______________________________________
[[ 0.78698148 -1.46127729  0.3832138 ]
 [-1.23752721  0.61720976  0.36778896]
 [ 1.56384386  0.2263411  -1.24657446]]


Ejercicio 9:

Calcular la suma de los elementos diagonales de una matriz de 3x3.

In [12]:
import numpy as np 
matris=np.random.random((3,3))
diagonal = np.trace(matris)
print(matris)
print("la suma de la diagonal es: ")
print(diagonal)

[[0.74850337 0.30006124 0.56844737]
 [0.17463929 0.19524738 0.37170394]
 [0.58645306 0.52584946 0.25034801]]
la suma de la diagonal es: 
1.1940987686121531


Ejercicio 10:

Encuentra los índices de elementos distintos de cero de [1,2,0,0,4,0].

In [14]:
import numpy as np
matris=np.array([1,2,0,0,4,0])
non_zero_indices = np.nonzero(matris)
print(non_zero_indices)

(array([0, 1, 4]),)
