Ejercicio 71:

Cree una matriz 1D y establezca los valores entre 10 y 20 en 0.

In [3]:
import numpy as np

arr=np.array([5, 15, 12, 18, 25])
arr[(arr>=10) & (arr<=20)]=0
print(arr)



[ 5  0  0  0 25]


Ejercicio 72:

Calcular el seno hiperbólico inverso de cada elemento de una matriz 1D.

In [4]:
import numpy as np 
array=np.array([1, 2, 3, 4])
inverso=np.arcsinh(arr)
print(inverso)

[2.31243834 0.         0.         0.         3.91242277]


Ejercicio 73:

Calcular el producto Kronecker de dos matrices.

In [5]:
import numpy as np 

arr1=np.array([1,2])
arr2=np.array([3,4])
pro=np.kron(arr1,arr2)
print(pro)

[3 4 6 8]


Ejercicio 74:

Calcular la desviación absoluta media de una matriz 1D.

In [6]:
import numpy as np

arr=np.array([1,2,3,4,5])
desviacion=np.mean(np.abs(arr - np.mean(arr)))
print(arr)

[1 2 3 4 5]


Ejercicio 75:

Crea una matriz de 3x3 y establece todos los valores por encima de la diagonal principal en cero.

In [ ]:
import numpy as np 

matris=np.random.random((3,3))
matris[np.triu_indices(3, 1)] = 0
print(matris)

Ejercicio 76:

Cuente el número de ocurrencias de cada valor único en una matriz 1D.

In [ ]:
import numpy as np
arr = np.array([2, 2, 1, 3, 3, 3, 4])
unique_values, counts = np.unique(arr, return_counts=True)
print("Unique values:", unique_values)
print("Counts:", counts)

Ejercicio 77:

Calcular el producto acumulativo de elementos a lo largo de un eje dado en una matriz 2D.

In [ ]:
import numpy as np
matrix = np.random.random((3, 4))
cumulative_product_axis0 = np.cumprod(matrix, axis=0)
print(cumulative_product_axis0)

Ejercicio 78:

Redondea los elementos de una matriz 1D al entero más cercano.

In [ ]:
import numpy as np
arr = np.array([1.2, 2.7, 3.5, 4.9])
rounded_arr = np.round(arr)
print(rounded_arr)

Ejercicio 79:

Crea una matriz 1D y añade un nuevo elemento al final.

In [ ]:
import numpy as np
arr = np.array([1, 2, 3])
new_element = 4
arr = np.append(arr, new_element)
print(arr)

Ejercicio 80:

Calcular la diferencia absoluta elemento por elemento entre dos matrices.

In [ ]:
import numpy as np
arr1 = np.array([3, 7, 1, 10, 4])
arr2 = np.array([2, 5, 8, 1, 7])
absolute_difference = np.abs(arr1 - arr2)
print(absolute_difference)